import Navbar from "@/components/navbarLO";
import "./globals.css";

export const metadata = {
  title: "AutoLife",
  description: "Generated by create next app",
};

export default function vehiculoPublicoRout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-white">
          <Navbar></Navbar>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
