import { cookies } from 'next/headers'
import "./globals.css";
import NavBarD from "@/components/NavBar/navbarD";


export const metadata = {
  title: "AutoLife",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cook = cookies().get("authToken");
  var token = null;
  var Usuario = null;
  if (cook != undefined && cook != "") {
    token = cook.value;
  }
    
  //validacion del token

  if (token != undefined && token != "") {
    var verificacion = null;
    try {
      const Verify_Url = `${process.env.HOSTNAME}/auth/verify`;
      const response = await fetch(Verify_Url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ token: token })
      });
      verificacion = await response.json();
    } catch (error) {
      console.log(error)
    }

    // cargar datos del usuario

    try {
      const Usuario_API_URL = `${process.env.HOSTNAME}/api/usuarios/list/nombreusuario/${verificacion.userLogin}`;
      const response = await fetch(Usuario_API_URL, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        }
      });
      Usuario = await response.json()
    } catch (error) {
      console.log(error)
    }

  }
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/imagenes/logo/logoSLSF.png" />
      </head>
      <body>
        <header className="bg-white">
          <NavBarD usuario={Usuario} />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
