import "./globals.css";
import NavbarLO from "@/components/NavBar/navbarLO";


export const metadata = {
  title: "AutoLife",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-white">
          <NavbarLO></NavbarLO>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
