import NavbarLi from "@/components/NavBar/navbarLi";
import "./globals.css";
import { cookies } from 'next/headers'


export const metadata = {
  title: "AutoLife",
  description: "Generated by create next app",
};

export default async function LogedLayout({ Children }) {
  const XD = cookies().get("authToken");
  var token = null;
  var Usuario = null;
  var Vehiculos = null;
  var error = false;
  if (XD != undefined && XD != "") {
    token = XD.value;
  }

  //validacion del token

  if (token != undefined && token != "") {
    var verificacion = null;
    try {
      const Verify_Url = "http://localhost:8090/auth/verify";
      const response = await fetch(Verify_Url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ token: token })
      });
      verificacion = await response.json();
    } catch (error) {
      console.log(error)
    }

    // cargar datos del usuario

    try {
      const Usuario_API_URL = `http://localhost:8090/api/usuarios/list/nombreusuario/${verificacion.userLogin}`;
      const response = await fetch(Usuario_API_URL, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        }
      });
      Usuario = await response.json()
    } catch (error) {
      console.log(error)
    }

    // cargar datos de los vehiculos del usuario

    try {
      const Vehiculos_API_URL = `http://localhost:8090/api/vehiculo/list/usuario/${Usuario.dni}`;
      const response = await fetch(Vehiculos_API_URL, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        }
      });
      Vehiculos = await response.json();
    } catch (error) {
      console.log(error)
    }
  } else {
    error = true;
  }

  return (
    <html lang="en">
      <body>
        <header className="bg-white">
          <NavbarLi usuario={Usuario}></NavbarLi>
        </header>
        <main>
          {Children}
        </main>
      </body>
    </html>
  );
}
